config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :categories
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
 mount_uploader :image, ImageUploader
 has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
 belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :image)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :start_date, :due_date, :completed, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @category.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h4>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :image, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="page-header">
  <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @category, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing category</h1>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="page-header">
  <%= link_to new_category_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Category
  <% end %>
  <h1>Listing categories</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Image</th>
            <th>Actions</th>
       
       
      </tr>
    </thead>

    <tbody>
    <% @categories.each do |category| %>
    <tr>
            <td><%= category.title %></td>
            <td><%= image_tag(category.image_url, width: 600) if
       category.image.present? %></td>
            

        <td><%= link_to 'Edit', edit_category_path(category) %>
      
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<div class="page-header">
  <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New category</h1>
</div>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="page-header">

  <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_category_path(@category), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show category</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @category.title %></dd>

  <dt>Image:</dt>
  <dd><%= image_tag(@category.image_url, width: 600) if
       @category.image.present? %></dd>

</dl>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Start date</th>
            <th>Due date</th>
            <th>Completed</th>
          
         
            
      </tr>
    </thead>

    <tbody>
     <% @category.tasks.each do |task| %>
     <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.start_date %></td>
        <td><%= task.due_date %></td>
          <% if task.completed %>
           <td><span class="badge badge-success">Done</span></td>
          <% else %>
            <td><span class="badge badge-danger">To Do</span></td>
          <% end %>
       
        
    </tr>
     
     <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
     <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
 <%= link_to "Planner", "/", class: "navbar-brand" %>
 </div>
 <div id="navbar" class="collapse navbar-collapse">
 <ul class="nav navbar-nav">
 <li><a href="/tasks/new">New task</a></li>
 <li><a href="/categories">Category</a></li>
 </ul>
 </div>
     
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @task.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h4>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :start_date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :due_date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :due_date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :completed, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :completed, class: "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
      <%= f.label :category, class: "col-sm-2 control-label" %><br>
      <%= f.collection_select(:category_id, Category.all, :id, :title, {:prompt =>
       'Please select the category of this task'}) %>
</div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @task, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing task</h1>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
  <%= link_to new_task_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Task
  <% end %>
  <h1>Listing tasks</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Start date</th>
            <th>Due date</th>
            <th>Completed</th>
           
            <th>Date</th>
         
            
      </tr>
    </thead>

    <tbody>
     <% @tasks.each do |task| %>
     <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.start_date %></td>
        <td><%= task.due_date %></td>
          <% if task.completed %>
           <td><span class="badge badge-success">Done</span></td>
          <% else %>
            <td><span class="badge badge-danger">To Do</span></td>
          <% end %>
        <td><%= link_to 'Edit', edit_task_path(task) %>
             <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>

        <td><%= task.created_at %></td>
    </tr>
     
     <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/new.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New task</h1>
</div>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_task_path(@task), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show task</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @task.title %></dd>

  <dt>Description:</dt>
  <dd><%= @task.description %></dd>

  <dt>Start date:</dt>
  <dd><%= @task.start_date %></dd>

  <dt>Due date:</dt>
  <dd><%= @task.due_date %></dd>

  <dt>Completed:</dt>
  <dd><%= @task.completed %></dd>

</dl>